/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FlightFlightIdRouteImport } from './routes/flight.$flightId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightFlightIdRoute = FlightFlightIdRouteImport.update({
  id: '/flight/$flightId',
  path: '/flight/$flightId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/flight/$flightId': typeof FlightFlightIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/flight/$flightId': typeof FlightFlightIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/confirmation': typeof ConfirmationRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/flight/$flightId': typeof FlightFlightIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/bookings'
    | '/confirmation'
    | '/payment'
    | '/search'
    | '/flight/$flightId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/bookings'
    | '/confirmation'
    | '/payment'
    | '/search'
    | '/flight/$flightId'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/bookings'
    | '/confirmation'
    | '/payment'
    | '/search'
    | '/flight/$flightId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  BookingsRoute: typeof BookingsRoute
  ConfirmationRoute: typeof ConfirmationRoute
  PaymentRoute: typeof PaymentRoute
  SearchRoute: typeof SearchRoute
  FlightFlightIdRoute: typeof FlightFlightIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/$flightId': {
      id: '/flight/$flightId'
      path: '/flight/$flightId'
      fullPath: '/flight/$flightId'
      preLoaderRoute: typeof FlightFlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  BookingsRoute: BookingsRoute,
  ConfirmationRoute: ConfirmationRoute,
  PaymentRoute: PaymentRoute,
  SearchRoute: SearchRoute,
  FlightFlightIdRoute: FlightFlightIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
